import { DEFAULT_REGISTRY } from '@opencara/shared';
import { validateCommandBinary } from './tool-executor.js';
import { CONFIG_FILE, ensureConfigDir } from './config.js';
import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as readline from 'node:readline';

/** Tools to scan for — restricted set per project owner decision. */
export const SCANNABLE_TOOLS = ['claude', 'codex', 'gemini'] as const;

/** Cost-effective default models per tool. */
export const DEFAULT_MODELS: Record<string, string> = {
  claude: 'claude-sonnet-4-6',
  codex: 'gpt-5-codex',
  gemini: 'gemini-2.5-pro',
};

/** Install links for each scannable tool. */
const INSTALL_LINKS: Record<string, string> = {
  claude: 'https://docs.anthropic.com/en/docs/claude-code',
  codex: 'https://github.com/openai/codex',
  gemini: 'https://github.com/google-gemini/gemini-cli',
};

export interface DiscoveredTool {
  toolName: string;
  defaultModel: string;
  maxTasksPerDay: number;
}

export interface PrerequisiteCheck {
  git: boolean;
  gh: boolean;
  /** Only meaningful when gh is true. */
  ghAuthenticated: boolean;
  /** GitHub username if authenticated, null otherwise. */
  ghUsername: string | null;
}

/** Check that prerequisite binaries (git, gh) are installed and gh auth status. */
export function checkPrerequisites(): PrerequisiteCheck {
  const gitInstalled = validateCommandBinary('git');
  const ghInstalled = validateCommandBinary('gh');
  let ghAuthenticated = false;
  let ghUsername: string | null = null;

  if (ghInstalled) {
    try {
      execFileSync('gh', ['auth', 'status'], { stdio: 'pipe' });
      ghAuthenticated = true;
      try {
        ghUsername = execFileSync('gh', ['api', '/user', '--jq', '.login'], {
          stdio: 'pipe',
        })
          .toString()
          .trim();
      } catch {
        // username fetch is best-effort
      }
    } catch {
      ghAuthenticated = false;
    }
  }

  return { git: gitInstalled, gh: ghInstalled, ghAuthenticated, ghUsername };
}

/** Scan for installed AI tools from the SCANNABLE_TOOLS list. */
export function discoverTools(): Omit<DiscoveredTool, 'maxTasksPerDay'>[] {
  const results: Omit<DiscoveredTool, 'maxTasksPerDay'>[] = [];

  for (const toolName of SCANNABLE_TOOLS) {
    if (validateCommandBinary(toolName)) {
      const defaultModel = resolveDefaultModel(toolName);
      results.push({ toolName, defaultModel });
    }
  }

  return results;
}

/**
 * Resolve the default model for a tool.
 * Uses DEFAULT_MODELS map, falls back to the first model in the registry for the tool.
 */
export function resolveDefaultModel(toolName: string): string {
  if (DEFAULT_MODELS[toolName]) {
    return DEFAULT_MODELS[toolName];
  }
  const registryModel = DEFAULT_REGISTRY.models.find((m) => m.tools.includes(toolName));
  return registryModel?.name ?? toolName;
}

/** Generate config.toml content from discovered tools with per-tool limits. */
export function generateConfig(tools: DiscoveredTool[]): string {
  const lines: string[] = [
    '# Auto-generated by opencara — edit to customize',
    '# See: https://docs.opencara.com/configuration',
    '',
  ];

  for (const tool of tools) {
    lines.push('[[agents]]');
    lines.push(`tool = "${tool.toolName}"`);
    lines.push(`model = "${tool.defaultModel}"`);
    lines.push('roles = ["reviewer", "summarizer"]');
    lines.push(`max_tasks_per_day = ${tool.maxTasksPerDay}`);
    lines.push('');
  }

  return lines.join('\n');
}

/** Ask a question on stdout/stdin, return the trimmed answer. */
async function prompt(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

/** Ask for a positive integer with a default, re-prompting on invalid input. */
async function promptPositiveInt(
  rl: readline.Interface,
  label: string,
  defaultValue: number,
): Promise<number> {
  while (true) {
    const answer = await prompt(rl, `  ${label} — max tasks per day [${defaultValue}]: `);
    if (answer === '') return defaultValue;
    const parsed = parseInt(answer, 10);
    if (Number.isInteger(parsed) && parsed > 0) return parsed;
    process.stdout.write('  Please enter a positive integer.\n');
  }
}

/**
 * Interactive first-run setup.
 *
 * Checks prerequisites, scans for tools, asks per-tool daily limits,
 * optionally writes config.toml.
 *
 * Returns true if config was written, false if user declined or no tools found.
 * Exits the process if git is missing (hard requirement).
 *
 * Only runs when stdin is a TTY; non-TTY returns false without printing anything
 * (caller is responsible for the "no config found" error in non-TTY mode).
 */
export async function interactiveSetup(): Promise<boolean> {
  if (!process.stdin.isTTY) {
    return false;
  }

  process.stdout.write('\nNo config found at ~/.opencara/config.toml\n');
  process.stdout.write('\nChecking prerequisites...\n');

  const prereqs = checkPrerequisites();

  if (prereqs.git) {
    process.stdout.write('  \u2713 git\n');
  } else {
    process.stdout.write('  \u2717 git (not found)\n\n');
    process.stdout.write('git is required for opencara. Install it:\n');
    process.stdout.write('  macOS:   brew install git\n');
    process.stdout.write('  Ubuntu:  sudo apt install git\n');
    process.stdout.write('  Windows: https://git-scm.com/download/win\n');
    process.exit(1);
    return false; // unreachable, but satisfies TypeScript
  }

  if (prereqs.gh) {
    if (prereqs.ghAuthenticated && prereqs.ghUsername) {
      process.stdout.write(`  \u2713 gh (GitHub CLI) \u2014 logged in as @${prereqs.ghUsername}\n`);
    } else if (prereqs.ghAuthenticated) {
      process.stdout.write('  \u2713 gh (GitHub CLI) \u2014 authenticated\n');
    } else {
      process.stdout.write('  \u2713 gh (GitHub CLI)\n');
      process.stdout.write('  \u26a0 gh: not logged in\n\n');
      process.stdout.write(
        'gh authentication is recommended for private repo access and codebase checkout.\n',
      );
      process.stdout.write('Run: gh auth login\n');
      process.stdout.write('Continuing without gh auth \u2014 some features may be limited.\n');
    }
  } else {
    process.stdout.write('  \u2717 gh (not found)\n\n');
    process.stdout.write(
      '\u26a0 GitHub CLI (gh) is recommended for private repo support and codebase checkout.\n',
    );
    process.stdout.write('  Install: https://cli.github.com\n');
    process.stdout.write('Continuing without gh \u2014 some features may be limited.\n');
  }

  process.stdout.write('\nScanning for AI tools...\n');

  const found = discoverTools();
  for (const tool of SCANNABLE_TOOLS) {
    const disc = found.find((t) => t.toolName === tool);
    if (disc) {
      process.stdout.write(`  \u2713 ${tool} (${disc.defaultModel})\n`);
    } else {
      process.stdout.write(`  \u2717 ${tool} (not found)\n`);
    }
  }

  if (found.length === 0) {
    process.stdout.write('\nNo AI tools found. Install one of: claude, codex, gemini\n');
    for (const tool of SCANNABLE_TOOLS) {
      process.stdout.write(`  ${tool}:  ${INSTALL_LINKS[tool]}\n`);
    }
    return false;
  }

  process.stdout.write(
    `\nFound ${found.length} tool${found.length > 1 ? 's' : ''}. Configure each tool:\n\n`,
  );

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  try {
    const toolsWithLimits: DiscoveredTool[] = [];
    for (const tool of found) {
      const maxTasksPerDay = await promptPositiveInt(rl, tool.toolName, 1);
      toolsWithLimits.push({ ...tool, maxTasksPerDay });
    }

    const answer = await prompt(rl, '\nGenerate config.toml with these settings? (Y/n) ');
    if (answer.toLowerCase() === 'n' || answer.toLowerCase() === 'no') {
      process.stdout.write('\nSkipped. Create config manually at ~/.opencara/config.toml\n');
      process.stdout.write('See: https://docs.opencara.com/configuration\n');
      return false;
    }

    const content = generateConfig(toolsWithLimits);
    ensureConfigDir();
    fs.writeFileSync(CONFIG_FILE, content, { encoding: 'utf-8', mode: 0o600 });
    process.stdout.write('\nConfig written to ~/.opencara/config.toml\n');
    return true;
  } finally {
    rl.close();
  }
}
